In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('/kaggle/input/datasets/pavankumar2910/student-performance/dataofstudents (1).xlsx')

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [3]:
import sqlite3

conn = sqlite3.connect(':memory:')
df.to_sql('students', conn, index=False, if_exists='replace')

6607

In [4]:
pd.read_sql("""
SELECT AVG(Exam_Score) AS avg_score
FROM students
""", conn)

   avg_score
0  67.235659

In [12]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN Hours_Studied < 5 THEN 'Low Study'
        WHEN Hours_Studied BETWEEN 5 AND 10 THEN 'Medium Study'
        ELSE 'High Study'
    END AS Study_Category,
    AVG(Exam_Score) AS avg_score
FROM students
GROUP BY Study_Category;
""", conn)

  Study_Category  avg_score
0     High Study  67.426786
1      Low Study  62.500000
2   Medium Study  64.137615

In [14]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN Attendance < 60 THEN 'Low Attendance'
        WHEN Attendance BETWEEN 60 AND 80 THEN 'Medium Attendance'
        ELSE 'High Attendance'
    END AS Attendance_Level,
    AVG(Exam_Score) AS avg_score
FROM students
GROUP BY Attendance_Level;
""", conn)

    Attendance_Level  avg_score
0    High Attendance  69.244347
1  Medium Attendance  65.367222

In [16]:
pd.read_sql("""
SELECT Gender, AVG(Exam_Score) AS avg_score
FROM students
GROUP BY Gender;
""", conn)

   Gender  avg_score
0  Female  67.244898
1    Male  67.228894

In [15]:
pd.read_sql("""
SELECT MAX(Exam_Score) FROM students;
""", conn)

   MAX(Exam_Score)
0              101

In [8]:
pd.read_sql("""
SELECT MIN(Exam_Score) FROM students;
""", conn)

   MIN(Exam_Score)
0               55

In [9]:
pd.read_sql("""
SELECT AVG(Exam_Score) FROM students;
""", conn)

   AVG(Exam_Score)
0        67.235659

In [10]:
pd.read_sql("""
SELECT COUNT(*) FROM students;
""", conn)

   COUNT(*)
0      6607

In [11]:
pd.read_sql("""
SELECT 
    CASE 
        WHEN Exam_Score >= 50 THEN 'Pass'
        ELSE 'Fail'
    END AS Result,
    COUNT(*) AS total_students
FROM students
GROUP BY Result;
""", conn)

  Result  total_students
0   Pass            6607